name: Update contents

on:
  workflow_dispatch:



permissions:
  contents: write

concurrency:
  group: "auto"
  cancel-in-progress: false

jobs:
  deploy-reusable:
    uses: ./.github/workflows/deploy.yaml
    permissions:
      contents: write
      pages: write
      id-token: write
    secrets:
      NOTES_ACCESS_TOKEN: ${{ secrets.NOTES_ACCESS_TOKEN }}

    steps:
      - name: Push to GitHub
        id: push
        run: |
          git status
