name: Update contents

on:
  workflow_dispatch:



permissions:
  contents: write

concurrency:
  group: "auto"
  cancel-in-progress: false

jobs:
  deploy-reusable:
    uses: ./.github/workflows/deploy.yaml
    permissions:
      contents: write
      pages: write
      id-token: write
    secrets:
      NOTES_ACCESS_TOKEN: ${{ secrets.NOTES_ACCESS_TOKEN }}

  push:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs: deploy-reusable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v5
        with:
          name: repo
          path: .
      - name: Push to GitHub
        id: push
        run: |
          set -x
          ls -lah .
          git status
          git diff
          cd content
          git status
          cd ..
          git config --global user.name "GLR"
          git config --global user.email "GLR@users.noreply.github.com"
          git add content
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -m "Auto update of content [skip ci]"
          git push
