name: Update contents

on:
  workflow_dispatch:



permissions:
  contents: write

concurrency:
  group: "auto"
  cancel-in-progress: false

jobs:
  deploy-reusable:
    uses: ./.github/workflows/deploy.yaml
    permissions:
      contents: write
      pages: write
      id-token: write
    secrets:
      NOTES_ACCESS_TOKEN: ${{ secrets.NOTES_ACCESS_TOKEN }}

  push:
    needs: deploy-reusable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: repo
          path: .
      - name: Push to GitHub
        id: push
        run: |
          ls -lah .
          git status
          cd contents
          git status
